name: Java Gradle Test Workflow

on:
  workflow_dispatch:
    inputs:
      test-pattern:
        description: 'Test pattern to run (e.g., storeAPI.*)'
        required: true
        default: 'storeAPI.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Print Gradle version
        run: ./gradlew --version

      - name: Install dependencies 
        run: ./gradlew build --no-daemon --stacktrace --exclude-task test

      - name: Print Gradle dependencies
        run: ./gradlew dependencies

      - name: Run tests from specific folder
        run: ./gradlew test --tests "${{ github.event.inputs.test-pattern }}" --stacktrace
       
      - name: Generate Allure Report
        run: ./gradlew allureReport
        if: always()  

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: build/allure-results
        if: always()  
        
